# Generated by Django 5.0.3 on 2024-03-18 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AddField(
            model_name='user',
            name='copropriete_gere',
            field=models.CharField(default='Valeur par defeaut', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='mail',
            field=models.EmailField(default='email@exemple.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='nom',
            field=models.CharField(default='Nom par defeaut', max_length=225),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='prenom',
            field=models.CharField(default='Prenom par defeaut', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='telephone',
            field=models.CharField(default='1234567890', help_text='Format: +1234567890', max_length=20),
            preserve_default=False,
        ),
    ]
